import AppIntents

// MARK: - App Shortcuts Provider
//
// Centralized shortcuts provider for the app.
// References intents generated by @Persistable macro on TaskItem and PersistentProject.
//
// Note: AppShortcutsProvider cannot be macro-generated due to AppIntents metadata
// processor limitations - it requires static analysis of non-macro Swift files.
//
// Having a single AppShortcutsProvider is recommended by Apple for:
// - Consistent shortcut organization
// - Easier management of phrases across entity types
// - Better Siri integration

struct ShowcaseShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        // Task shortcuts
        AppShortcut(
            intent: TaskItem.TaskItemCreateIntent(),
            phrases: [
                "Create a task in \(.applicationName)",
                "New task in \(.applicationName)",
                "Add task to \(.applicationName)"
            ],
            shortTitle: "Create Task",
            systemImageName: "plus.circle"
        )
        AppShortcut(
            intent: TaskItem.TaskItemListIntent(),
            phrases: [
                "Show my tasks in \(.applicationName)",
                "List tasks in \(.applicationName)",
                "View tasks in \(.applicationName)"
            ],
            shortTitle: "List Tasks",
            systemImageName: "checklist"
        )
        AppShortcut(
            intent: TaskItem.TaskItemDeleteIntent(),
            phrases: [
                "Delete task in \(.applicationName)",
                "Remove task from \(.applicationName)"
            ],
            shortTitle: "Delete Task",
            systemImageName: "trash"
        )

        // Project shortcuts
        AppShortcut(
            intent: PersistentProject.PersistentProjectCreateIntent(),
            phrases: [
                "Create a project in \(.applicationName)",
                "New project in \(.applicationName)",
                "Add project to \(.applicationName)"
            ],
            shortTitle: "Create Project",
            systemImageName: "folder.badge.plus"
        )
        AppShortcut(
            intent: PersistentProject.PersistentProjectListIntent(),
            phrases: [
                "Show my projects in \(.applicationName)",
                "List projects in \(.applicationName)",
                "View projects in \(.applicationName)"
            ],
            shortTitle: "List Projects",
            systemImageName: "folder"
        )
    }
}
