import Foundation
import SwiftUI
import Archery

// MARK: - @SharedModel Demo
//
// The @SharedModel macro generates code for sharing data between:
// - Main app
// - Widgets (TimelineEntry conformance)
// - App Intents (AppEntity conformance)
// - Live Activities (ActivityAttributes conformance)
//
// Note: This macro requires a Widget extension target to fully demonstrate.
// The macro generates:
// - timestamp/relevanceScore for widgets
// - id/title for intents
// - Entity query stub
// - ActivityAttributes ContentState
//
// Example usage (in a Widget target):
// @SharedModel(widget: true, intent: true, liveActivity: false)
// struct TaskEntry: Codable, Hashable {
//     var name: String
//     var dueDate: Date
// }

// Sample data model showing what the macro would enhance
struct TaskEntryExample: Codable, Hashable, Identifiable {
    var id: String = UUID().uuidString
    var name: String
    var dueDate: Date
    var priority: Int
    var isCompleted: Bool

    // These would be generated by @SharedModel(widget: true)
    var timestamp: Date?
    var relevanceScore: Float?

    // This would be generated by @SharedModel(intent: true)
    var title: String? { name }

    init(name: String, dueDate: Date, priority: Int = 1, isCompleted: Bool = false) {
        self.name = name
        self.dueDate = dueDate
        self.priority = priority
        self.isCompleted = isCompleted
    }
}

// MARK: - Showcase View (always available)

struct SharedModelShowcaseView: View {
    var body: some View {
        List {
            Section {
                Text("@SharedModel generates code for sharing data between your app, widgets, App Intents, and Live Activities.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Section("Generated for Widgets") {
                GeneratedMemberRow(
                    name: "timestamp: Date?",
                    description: "Required for TimelineEntry"
                )
                GeneratedMemberRow(
                    name: "relevanceScore: Float?",
                    description: "For timeline relevance sorting"
                )
                GeneratedMemberRow(
                    name: "TimelineEntry conformance",
                    description: "date and relevance computed properties"
                )
            }

            Section("Generated for App Intents") {
                GeneratedMemberRow(
                    name: "id: String",
                    description: "Unique identifier for the entity"
                )
                GeneratedMemberRow(
                    name: "title: String?",
                    description: "Display title for the entity"
                )
                GeneratedMemberRow(
                    name: "AppEntity conformance",
                    description: "typeDisplayRepresentation, displayRepresentation"
                )
                GeneratedMemberRow(
                    name: "Query struct",
                    description: "EntityQuery implementation stub"
                )
            }

            Section("Generated for Live Activities") {
                GeneratedMemberRow(
                    name: "activityId: String?",
                    description: "Live Activity identifier"
                )
                GeneratedMemberRow(
                    name: "isStale: Bool",
                    description: "Track if activity is outdated"
                )
                GeneratedMemberRow(
                    name: "ContentState struct",
                    description: "status, progress, updatedAt"
                )
            }

            Section("Usage") {
                VStack(alignment: .leading, spacing: 4) {
                    Text("@SharedModel(")
                        .font(.caption.monospaced())
                    Text("    widget: true,")
                        .font(.caption.monospaced())
                    Text("    intent: true,")
                        .font(.caption.monospaced())
                    Text("    liveActivity: false")
                        .font(.caption.monospaced())
                    Text(")")
                        .font(.caption.monospaced())
                    Text("struct TaskEntry {")
                        .font(.caption.monospaced())
                    Text("    var name: String")
                        .font(.caption.monospaced())
                    Text("    var dueDate: Date")
                        .font(.caption.monospaced())
                    Text("}")
                        .font(.caption.monospaced())
                }
                .padding(8)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color(.secondarySystemBackground))
                .clipShape(RoundedRectangle(cornerRadius: 8))
            }

            Section("Requirements") {
                RequirementRow(
                    framework: "WidgetKit",
                    forFeature: "widget: true",
                    icon: "square.grid.2x2"
                )
                RequirementRow(
                    framework: "AppIntents",
                    forFeature: "intent: true",
                    icon: "sparkles"
                )
                RequirementRow(
                    framework: "ActivityKit",
                    forFeature: "liveActivity: true",
                    icon: "bell.badge"
                )
            }

            Section("Live Example") {
                let entry = TaskEntryExample(
                    name: "Review PR",
                    dueDate: Date().addingTimeInterval(3600),
                    priority: 2
                )

                VStack(alignment: .leading, spacing: 8) {
                    LabeledContent("Name", value: entry.name)
                    LabeledContent("Due", value: entry.dueDate.formatted())
                    LabeledContent("Priority", value: "\(entry.priority)")
                    LabeledContent("ID", value: entry.id)
                        .font(.caption.monospaced())

                    Text("The fields above would be enhanced with macro-generated properties for widgets, intents, and live activities.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .padding(.top, 4)
                }
            }
        }
        .navigationTitle("@SharedModel")
    }
}

private struct GeneratedMemberRow: View {
    let name: String
    let description: String

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text(name)
                    .font(.subheadline.monospaced())
                Text(description)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            Image(systemName: "plus.circle.fill")
                .foregroundStyle(.blue)
        }
    }
}

private struct RequirementRow: View {
    let framework: String
    let forFeature: String
    let icon: String

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.title3)
                .foregroundStyle(.tint)
                .frame(width: 28)

            VStack(alignment: .leading, spacing: 2) {
                Text(framework)
                    .font(.subheadline.weight(.medium))
                Text(forFeature)
                    .font(.caption.monospaced())
                    .foregroundStyle(.secondary)
            }
        }
    }
}

#Preview {
    NavigationStack {
        SharedModelShowcaseView()
    }
}
